/*
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#include "velox/experimental/ucx-exchange/Communicator.h"
#include <cuda_runtime.h>
#include <folly/system/ThreadName.h>
#include <ucxx/api.h>
#include <ucxx/utils/ucx.h>
#include <algorithm>
#include <iostream>
#include "velox/common/base/Exceptions.h"
#include "velox/experimental/cudf/CudfConfig.h"
#include "velox/experimental/ucx-exchange/CommElement.h"
#include "velox/experimental/ucx-exchange/EndpointRef.h"
#include "velox/experimental/ucx-exchange/UcxExchangeModules.h"
#include "velox/experimental/ucx-exchange/UcxExchangeServer.h"
#include "velox/experimental/ucx-exchange/UcxExchangeSource.h"

#include <glog/logging.h>

using namespace facebook::velox::cudf_velox;

DEFINE_bool(velox_ucx_exchange, false, "Enable Velox UCX exchange.");

namespace facebook::velox::ucx_exchange {

// static
std::once_flag Communicator::onceFlag;
std::mutex Communicator::instanceMutex_;
std::mutex Communicator::shutdownMutex_;
std::shared_ptr<Communicator> Communicator::instancePtr_ = nullptr;

/* static */
std::shared_ptr<Communicator> Communicator::initAndGet(
    uint16_t port,
    std::string_view coordinatorURL,
    ContinueFuture* future) {
  if (!CudfConfig::getInstance().exchange) {
    return nullptr;
  }
  std::call_once(onceFlag, [&] {
    auto instance = std::shared_ptr<Communicator>(new Communicator());
    instance->port_ = port;
    instance->coordinatorURL_ = coordinatorURL;
    // Generate a random unique worker ID for same-process detection.
    // std::random_device reads from /dev/urandom on Linux (non-blocking).
    // A 64-bit random value has negligible collision probability.
    std::random_device rd;
    std::mt19937_64 gen(rd());
    std::uniform_int_distribution<uint64_t> dist;
    instance->workerId_ = dist(gen);
    LOG(INFO) << "Communicator workerId=" << instance->workerId_;
    auto logLevel = CudfConfig::getInstance().exchangeLogLevel;
    LOG(INFO) << "ucx-exchange VLOG level set to " << logLevel;
    if (logLevel > 0) {
      // Set VLOG level for all ucx-exchange source files.
      // kUcxExchangeModules is auto-generated by CMake from the source list.
      for (const char* module : kUcxExchangeModules) {
        google::SetVLOGLevel(module, logLevel);
      }
    }
    if (future) {
      *future = instance->promise_.getSemiFuture();
    }
    {
      std::lock_guard<std::mutex> lock(instanceMutex_);
      instancePtr_ = std::move(instance);
    }
  });
  auto instance = tryGetInstance();
  VELOX_CHECK_NOT_NULL(
      instance,
      "Communicator was shut down and cannot be reinitialized in this process");
  VELOX_CHECK_EQ(
      instance->port_,
      port,
      "Cannot initialize communicator again with different port");
  return instance;
}

/* static */
std::shared_ptr<Communicator> Communicator::getInstance() {
  auto instance = tryGetInstance();
  VELOX_CHECK_NOT_NULL(
      instance, "Communicator not initialized or already shut down.");
  return instance;
}

/* static */
std::shared_ptr<Communicator> Communicator::tryGetInstance() {
  std::lock_guard<std::mutex> lock(instanceMutex_);
  return instancePtr_;
}

/* static */
void Communicator::shutdown() {
  std::lock_guard<std::mutex> shutdownLock(shutdownMutex_);
  auto instance = tryGetInstance();
  if (!instance) {
    return;
  }
  if (!instance->releaseResourcesAfterRun()) {
    return;
  }
  std::lock_guard<std::mutex> lock(instanceMutex_);
  if (instancePtr_ == instance) {
    instancePtr_.reset();
  }
}

/* static */ void Communicator::cStyleListenerCallback(
    ucp_conn_request_h conn_request,
    void* arg) {
  try {
    // Cast the argument back to our instance variable. Never let an exception
    // cross the UCX C callback boundary during terminal cancellation.
    Communicator* instance = static_cast<Communicator*>(arg);
    if (instance == nullptr || instance->isShuttingDown()) {
      return;
    }
    instance->listenerCallback(conn_request);
  } catch (const std::exception& e) {
    LOG(ERROR) << "Ignoring UCX listener callback during shutdown: "
               << e.what();
  } catch (...) {
    LOG(ERROR) << "Ignoring unknown UCX listener callback failure during "
                  "shutdown";
  }
}

/* static */ void Communicator::cStyleDataListenerCallback(
    ucp_conn_request_h conn_request,
    void* arg) {
  try {
    Communicator* instance = static_cast<Communicator*>(arg);
    if (instance == nullptr || instance->isShuttingDown()) {
      return;
    }
    instance->dataListenerCallback(conn_request);
  } catch (const std::exception& e) {
    LOG(ERROR) << "Ignoring UCX data-listener callback during shutdown: "
               << e.what();
  } catch (...) {
    LOG(ERROR) << "Ignoring unknown UCX data-listener callback failure during "
                  "shutdown";
  }
}

Communicator::~Communicator() {
  // Normal owners call shutdown() after joining run(). Keep destruction safe
  // during partial initialization and static finalization as a last resort.
  (void)releaseResourcesAfterRun();
  VLOG(3) << "Communicator destructed";
}

bool Communicator::releaseResourcesAfterRun() {
  if (running_.load(std::memory_order_acquire)) {
    LOG(ERROR) << "Communicator resources cannot be released before the "
                  "progress thread is stopped and joined";
    return false;
  }
  if (resourcesReleased_.load(std::memory_order_acquire)) {
    return true;
  }
  shuttingDown_.store(true, std::memory_order_release);

  // Stop accepting connections before releasing any element or endpoint. The
  // worker remains alive until all UCXX-backed children have been released.
  listener_.reset();
  dataListener_.reset();

  // Drop every parent-to-child reference while the singleton/local caller
  // still keeps this Communicator alive. CommElement holds only a weak
  // back-reference, so clearing these containers cannot re-enter this
  // destructor.
  std::set<std::shared_ptr<CommElement>, PtrAddressLess> elements;
  {
    std::lock_guard<std::mutex> lock(elemMutex_);
    elements.swap(elements_);
    numCommElements_.store(0, std::memory_order_relaxed);
  }
  for (const auto& element : elements) {
    try {
      element->close();
    } catch (const std::exception& e) {
      LOG(ERROR) << "Ignoring CommElement close failure during terminal UCX "
                    "shutdown: "
                 << e.what();
    } catch (...) {
      LOG(ERROR) << "Ignoring unknown CommElement close failure during "
                    "terminal UCX shutdown";
    }
  }

  workQueue_.closeAndDrain();
  deferredEndpointCleanup_.closeAndDrain();
  elements.clear();

  std::vector<std::shared_ptr<EndpointRef>> pendingEndpoints;
  pendingEndpoints.swap(pendingEndpointRemoval_);
  std::map<HostPort, std::shared_ptr<EndpointRef>> endpoints;
  std::map<uint64_t, std::shared_ptr<EndpointRef>> dataEndpoints;
  std::vector<std::shared_ptr<ucxx::Endpoint>> incomingDataEndpoints;
  {
    std::lock_guard<std::recursive_mutex> lock(endpointsMutex_);
    endpoints.swap(endpoints_);
    dataEndpoints.swap(dataEndpoints_);
    incomingDataEndpoints.swap(incomingDataEndpoints_);
  }
  std::map<ucp_ep_h, std::shared_ptr<EndpointRef>> acceptedEndpoints;
  acceptedEndpoints.swap(acceptor_.handleToEndpointRef_);

  // Endpoint installs a close callback whose shared callback argument is its
  // EndpointRef, while EndpointRef owns Endpoint. Explicitly close every
  // referenced endpoint to execute and clear that callback, breaking the
  // ownership cycle; closeBlocking() is idempotent for duplicates.
  // Do this outside the original maps: closeBlocking() progresses UCX and can
  // invoke callbacks, but shutdown/status gates turn them into no-ops without
  // re-entering a container being mutated.
  auto closeEndpoint = [&](const std::shared_ptr<EndpointRef>& endpoint) {
    if (!endpoint) {
      return;
    }
    try {
      if (endpoint->endpoint_ && endpoint->endpoint_->isAlive()) {
        endpoint->endpoint_->closeBlocking();
      }
    } catch (const std::exception& e) {
      LOG(ERROR) << "Ignoring endpoint close failure during terminal UCX "
                    "shutdown: "
                 << e.what();
    } catch (...) {
      LOG(ERROR) << "Ignoring unknown endpoint close failure during terminal "
                    "UCX shutdown";
    }
  };
  for (const auto& endpoint : pendingEndpoints) {
    closeEndpoint(endpoint);
  }
  for (const auto& [_, endpoint] : endpoints) {
    closeEndpoint(endpoint);
  }
  for (const auto& [_, endpoint] : dataEndpoints) {
    closeEndpoint(endpoint);
  }
  for (const auto& [_, endpoint] : acceptedEndpoints) {
    closeEndpoint(endpoint);
  }
  for (const auto& endpoint : incomingDataEndpoints) {
    if (!endpoint) {
      continue;
    }
    try {
      if (endpoint->isAlive()) {
        endpoint->closeBlocking();
      }
    } catch (const std::exception& e) {
      LOG(ERROR) << "Ignoring incoming data endpoint close failure during "
                    "terminal UCX shutdown: "
                 << e.what();
    } catch (...) {
      LOG(ERROR) << "Ignoring unknown incoming data endpoint close failure "
                    "during terminal UCX shutdown";
    }
  }
  pendingEndpoints.clear();
  endpoints.clear();
  dataEndpoints.clear();
  acceptedEndpoints.clear();
  incomingDataEndpoints.clear();

  if (worker_) {
    // close() above canceled element-owned requests. Cancel any additional
    // worker-owned AM/tag requests, then progress their callbacks while all
    // callback payloads in deferredRequests_ are still alive.
    try {
      worker_->cancelInflightRequests(3'000'000'000, 3);
      for (int attempt = 0; attempt < 3; ++attempt) {
        worker_->progress();
      }
    } catch (const std::exception& e) {
      LOG(ERROR) << "Ignoring worker cancellation failure during terminal "
                    "UCX shutdown: "
                 << e.what();
    } catch (...) {
      LOG(ERROR) << "Ignoring unknown worker cancellation failure during "
                    "terminal UCX shutdown";
    }
  }
  const auto incompleteRequests = std::count_if(
      deferredRequests_.begin(),
      deferredRequests_.end(),
      [](const auto& request) { return !request->isCompleted(); });
  if (incompleteRequests > 0) {
    LOG(WARNING) << "UCX terminal shutdown retained " << incompleteRequests
                 << " incomplete request(s) until worker destruction";
  }
  deferredRequests_.clear();

  worker_.reset();
  context_.reset();
  resourcesReleased_.store(true, std::memory_order_release);
  return true;
}

/// @brief Run doesn't return until stop() is called.
/// All operations of the communicator will be carried out in the thread
/// that calls run.
void Communicator::run() {
  // Name the UCX progress thread so it is identifiable in nsys / thread dumps
  // (it carries all cross-peer send/recv progress and the rendezvous waits).
  folly::setThreadName("ucx-progress");
  VLOG(3) << "Using error handling mode: "
          << CudfConfig::getInstance().ucxxErrorHandling << std::endl;
  VLOG(3) << "Using blocking progress mode: "
          << CudfConfig::getInstance().ucxxBlockingPolling << std::endl;

  running_.store(true);
  // Force CUDA context creation.
  auto cudaStatus = cudaFree(0);
  VELOX_CHECK(
      cudaStatus == cudaSuccess,
      "Failed to initialize CUDA context: {}",
      cudaGetErrorString(cudaStatus));

  // create the UCXX context, worker, listener-context etc.
  if (CudfConfig::getInstance().ucxxBlockingPolling) {
    context_ = ucxx::createContext({}, ucxx::Context::defaultFeatureFlags);
  } else {
    context_ = ucxx::createContext({}, UCP_FEATURE_TAG | UCP_FEATURE_AM);
  }
  LOG(INFO) << "UCX CUDA transport support="
            << (context_->hasCudaSupport() ? "enabled" : "disabled")
            << "; remote transfers will use "
            << (context_->hasCudaSupport() ? "direct device buffers"
                                           : "host staging");

  worker_ = context_->createWorker();

  if (CudfConfig::getInstance().ucxxBlockingPolling) {
    // Communicator is using blocking progress mode.
    worker_->initBlockingProgressMode();
  }

  listener_ = worker_->createListener(
      port_, Communicator::cStyleListenerCallback, this);
  dataListener_ = worker_->createListener(
      0, Communicator::cStyleDataListenerCallback, this);
  LOG(INFO) << "UCX listeners ready: controlPort=" << listener_->getPort()
            << " dataPort=" << dataListener_->getPort();

  // Setup the active message callback that handles the
  // initial handshake and creates the senders.
  ucxx::AmReceiverCallbackInfo info(kAmCallbackOwner, kAmCallbackId);
  worker_->registerAmReceiverCallback(info, &Acceptor::cStyleAMCallback);

  promise_.setValue();

  VLOG(3) << "Communicator running.";
  const bool blockingMode = CudfConfig::getInstance().ucxxBlockingPolling;
  while (running_) {
    try {
      // Periodic heartbeat for diagnostic logging.
      auto now = std::chrono::steady_clock::now();
      if (now - lastHeartbeat_ >= std::chrono::seconds(5)) {
        std::lock_guard<std::mutex> lock(elemMutex_);

        // GPU memory usage via CUDA runtime.
        size_t gpuFree = 0, gpuTotal = 0;
        auto memStatus = cudaMemGetInfo(&gpuFree, &gpuTotal);
        if (memStatus != cudaSuccess) {
          LOG(WARNING) << "cudaMemGetInfo failed: "
                       << cudaGetErrorString(memStatus);
        }
        size_t gpuUsedMB = (gpuTotal - gpuFree) / (1024 * 1024);
        size_t gpuFreeMB = gpuFree / (1024 * 1024);
        size_t gpuTotalMB = gpuTotal / (1024 * 1024);

        // Count ExSrv vs ExSrc elements.
        int numServers = 0, numSources = 0;
        for (const auto& elem : elements_) {
          if (dynamic_cast<UcxExchangeServer*>(elem.get())) {
            ++numServers;
          } else if (dynamic_cast<UcxExchangeSource*>(elem.get())) {
            ++numSources;
          }
        }

        size_t numEndpoints;
        {
          std::lock_guard<std::recursive_mutex> lock(endpointsMutex_);
          numEndpoints = endpoints_.size();
        }
        VLOG(2) << "[COMM-HEARTBEAT] workQueue=" << workQueue_.size()
                << " elements=" << elements_.size()
                << " (servers=" << numServers << " sources=" << numSources
                << ")"
                << " endpoints=" << numEndpoints
                << " deferredCleanup=" << deferredEndpointCleanup_.size()
                << " deferredRequests=" << deferredRequests_.size()
                << " workItemsProcessed=" << workItemsProcessed_
                << " GPU=" << gpuUsedMB << "/" << gpuTotalMB << "MB"
                << " (free=" << gpuFreeMB << "MB)";
        VELOX_DCHECK_EQ(
            numCommElements_.load(std::memory_order_relaxed), elements_.size());
        workItemsProcessed_ = 0;
        lastHeartbeat_ = now;
      }

      // Process deferred endpoint cleanups from callbacks.
      // UCX callbacks cannot call closeBlocking() (which progresses the
      // worker) or iterate communicators_, so they defer cleanup to
      // this main loop via deferEndpointCleanup().
      while (auto ep = deferredEndpointCleanup_.pop()) {
        VLOG(3) << "Processing deferred endpoint cleanup";
        // Ask all communication elements to close, but don't closeBlocking()
        // the endpoint yet. Source close() schedules cleanUp() on the work
        // queue; closing the endpoint first turns those cleanups into
        // connection resets and hides the original producer-side error.
        ep->closeAndDrainCommunicators();
        pendingEndpointRemoval_.push_back(std::move(ep));
      }

      // Process the work queue. Make sure that communication is progressed
      // after each call to a comms element, otherwise we will deadlock.
      while (auto comms = workQueue_.pop()) {
        comms->process();
        ++workItemsProcessed_;
        // Progress after each work item to allow UCXX to advance
        // its internal state (complete sends/receives, fire callbacks).
        // Use non-blocking progress here to avoid blocking between
        // work items -- we want to drain the queue promptly.
        worker_->progress();
      }

      if (!pendingEndpointRemoval_.empty()) {
        for (auto& ep : pendingEndpointRemoval_) {
          removeEndpointRef(ep);
        }
        pendingEndpointRemoval_.clear();
      }

      // Clean up deferred requests that UCX has fully processed.
      // These are cancelled requests whose GPU buffers needed to stay
      // alive until UCX finished any in-flight operations on them.
      if (!deferredRequests_.empty()) {
        deferredRequests_.erase(
            std::remove_if(
                deferredRequests_.begin(),
                deferredRequests_.end(),
                [](const auto& req) { return req->isCompleted(); }),
            deferredRequests_.end());
      }
      // All queues are drained. Now wait for UCXX network events.
      // In blocking mode, this will block until a UCXX event arrives
      // or worker_->signal() is called (from addToWorkQueue,
      // deferEndpointCleanup, or stop).
      if (blockingMode) {
        // CUDA IPC/copy completions are not guaranteed to signal the UCX
        // worker event fd. Busy-progress while an exchange or a deferred
        // request is active; otherwise a rendezvous can sleep until an
        // unrelated signal arrives and serialize large GPU shuffles. Once the
        // communicator is idle, retain the indefinite wait to avoid burning a
        // CPU core per executor.
        const bool needsBusyProgress =
            numCommElements_.load(std::memory_order_relaxed) > 0 ||
            !deferredRequests_.empty();
        worker_->progressWorkerEvent(needsBusyProgress ? 0 : -1);
      } else {
        worker_->progress();
      }
    } catch (ucxx::IOError& e) {
      LOG(ERROR) << "In Communicator main loop UCXX Exception: " << e.what();
      throw;
    }
  }
  VLOG(3) << "Communicator stopping.";
}

/// @brief Stops the communicator, called from an outside thread.
void Communicator::stop() {
  shuttingDown_.store(true, std::memory_order_release);
  running_.store(false);
  signalWorker();
  // Only log fields that are safe to read from an outside thread.
  // endpoints_ is only accessed from the Communicator thread, so reading
  // it here would be a data race.
  VLOG(3) << "In Communicator::stop "
          << " elements: " << numCommElements_.load(std::memory_order_relaxed)
          << " workQueue_.size(): " << workQueue_.size();
}

void Communicator::registerCommElement(std::shared_ptr<CommElement> comms) {
  if (shuttingDown_.load(std::memory_order_acquire)) {
    return;
  }
  std::lock_guard<std::mutex> lock(elemMutex_);
  if (shuttingDown_.load(std::memory_order_acquire)) {
    return;
  }
  auto ret = elements_.insert(comms);
  VELOX_CHECK(ret.second, "CommElement already registered!");
  numCommElements_.fetch_add(1, std::memory_order_relaxed);
  // Also put the comms element into the work queue.
  workQueue_.push(comms);
  signalWorker();
}

void Communicator::signalWorker() {
  if (worker_ && CudfConfig::getInstance().ucxxBlockingPolling) {
    worker_->signal();
  }
}

void Communicator::addToWorkQueue(std::shared_ptr<CommElement> comms) {
  if (!comms || shuttingDown_.load(std::memory_order_acquire)) {
    return;
  }
  workQueue_.push(comms);
  signalWorker();
}

void Communicator::unregister(std::shared_ptr<CommElement> comms) {
  std::lock_guard<std::mutex> lock(elemMutex_);
  if (!comms) {
    return;
  }
  workQueue_.erase(comms);
  if (elements_.erase(comms) > 0) {
    const auto previous =
        numCommElements_.fetch_sub(1, std::memory_order_relaxed);
    VELOX_DCHECK_GT(previous, 0);
  }
}

std::shared_ptr<EndpointRef> Communicator::assocEndpointRef(
    std::shared_ptr<CommElement> comms,
    HostPort hostPort) {
  if (shuttingDown_.load(std::memory_order_acquire)) {
    return nullptr;
  }
  std::lock_guard<std::recursive_mutex> lock(endpointsMutex_);
  auto it = endpoints_.find(hostPort);
  if (it != endpoints_.end()) {
    std::shared_ptr<EndpointRef> ep = it->second;
    ep->addCommElem(comms);
    return ep;
  }
  // Socket endpoints are control-plane endpoints. Always enable peer error
  // handling so AM reply endpoints are valid and failures are reported. Bulk
  // exchange traffic uses getOrCreateDataEndpoint() instead.
  auto ep = worker_->createEndpointFromHostname(
      hostPort.hostname, hostPort.port, true);
  std::shared_ptr<EndpointRef> epRef = nullptr;
  if (ep != nullptr) {
    epRef = std::make_shared<EndpointRef>(
        ep, hostPort.hostname, std::to_string(hostPort.port));
    epRef->addCommElem(comms);
    ep->setCloseCallback(EndpointRef::onClose, epRef);
    endpoints_.insert(std::pair{hostPort, epRef});
  }
  return epRef;
}

void Communicator::removeEndpointRef(std::shared_ptr<EndpointRef> ep) {
  std::lock_guard<std::recursive_mutex> lock(endpointsMutex_);
  VLOG(2) << "[UCX-COMM-REMOVE-ENDPOINT] listenerPort=" << port_
          << " peer=" << (ep ? ep->getPeerAddress() : "(unknown)")
          << " endpointAlive="
          << (ep && ep->endpoint_ && ep->endpoint_->isAlive());

  // Close the endpoint if it's still alive.
  // NOTE: This calls closeBlocking() which progresses the worker internally,
  // which can fire listenerCallback() re-entrantly — hence the recursive mutex.
  // This method must NOT be called from within a UCX callback.
  // Use deferEndpointCleanup() from callbacks instead.
  if (ep->endpoint_ && ep->endpoint_->isAlive()) {
    VLOG(3) << "In Communicator::removeEndpointRef call closeBlocking";
    ep->endpoint_->closeBlocking();
  }
  for (auto it = endpoints_.begin(); it != endpoints_.end();) {
    if (it->second == ep) {
      it = endpoints_.erase(it);
    } else {
      ++it;
    }
  }
  for (auto it = acceptor_.handleToEndpointRef_.begin();
       it != acceptor_.handleToEndpointRef_.end();) {
    if (it->second == ep) {
      it = acceptor_.handleToEndpointRef_.erase(it);
    } else {
      ++it;
    }
  }
  VLOG(3) << "- Communicator::removeEndpointRef";
}

void Communicator::deferEndpointCleanup(std::shared_ptr<EndpointRef> ep) {
  // This method is safe to call from UCX callbacks because it doesn't
  // call any blocking/progress functions. The actual cleanup happens
  // in the main run() loop.
  VLOG(2) << "[UCX-COMM-DEFER-ENDPOINT-CLEANUP] peer="
          << (ep ? ep->getPeerAddress() : "(unknown)") << " endpointAlive="
          << (ep && ep->endpoint_ && ep->endpoint_->isAlive());
  if (shuttingDown_.load(std::memory_order_acquire)) {
    return;
  }
  deferredEndpointCleanup_.push(ep);
  signalWorker();
}

void Communicator::deferRequestCleanup(std::shared_ptr<ucxx::Request> request) {
  // Terminal element close() also deposits canceled requests here after the
  // progress thread has joined. Keep their callback payloads alive until the
  // finalizer has progressed worker cancellation.
  if (request && worker_) {
    deferredRequests_.push_back(std::move(request));
  }
}

std::shared_ptr<EndpointRef> Communicator::findEndpointRefByHandle(
    ucp_ep_h handle) {
  auto it = acceptor_.handleToEndpointRef_.find(handle);
  if (it != acceptor_.handleToEndpointRef_.end()) {
    return it->second;
  }
  return nullptr;
}

const std::string& Communicator::getCoordinatorUrl() {
  return coordinatorURL_;
}

std::string Communicator::getListenerIp() const {
  if (listener_) {
    return listener_->getIp();
  }
  return "";
}

uint16_t Communicator::getListenerPort() const {
  if (listener_) {
    return listener_->getPort();
  }
  return port_;
}

uint16_t Communicator::getDataListenerPort() const {
  VELOX_CHECK_NOT_NULL(dataListener_, "UCX data listener is not initialized");
  return dataListener_->getPort();
}

std::shared_ptr<EndpointRef> Communicator::getOrCreateDataEndpoint(
    uint64_t remoteWorkerId,
    std::string_view remoteHost,
    uint16_t remotePort) {
  VELOX_CHECK_NE(remoteWorkerId, 0, "Remote UCX worker id is zero");
  VELOX_CHECK(!remoteHost.empty(), "Remote UCX data host is empty");
  VELOX_CHECK_NE(remotePort, 0, "Remote UCX data port is zero");
  std::lock_guard<std::recursive_mutex> lock(endpointsMutex_);
  if (auto it = dataEndpoints_.find(remoteWorkerId);
      it != dataEndpoints_.end()) {
    return it->second;
  }
  auto endpoint = worker_->createEndpointFromHostname(
      std::string(remoteHost), remotePort, false);
  VELOX_CHECK_NOT_NULL(endpoint, "Failed to create UCX bulk-data endpoint");
  auto endpointRef = std::make_shared<EndpointRef>(
      endpoint, std::string(remoteHost), std::to_string(remotePort));
  dataEndpoints_.emplace(remoteWorkerId, endpointRef);
  LOG(INFO) << "Created UCX bulk-data endpoint with error handling disabled: "
            << "remoteWorkerId=" << remoteWorkerId << " peer=" << remoteHost
            << ":" << remotePort;
  return endpointRef;
}

/// @brief The callback method that is invoked when a client connects.
void Communicator::listenerCallback(ucp_conn_request_h conn_request) {
  if (shuttingDown_.load(std::memory_order_acquire)) {
    return;
  }
  char ip_str[INET6_ADDRSTRLEN];
  char port_str[INET6_ADDRSTRLEN];
  ucp_conn_request_attr_t attr{};

  attr.field_mask = UCP_CONN_REQUEST_ATTR_FIELD_CLIENT_ADDR;
  ucxx::utils::ucsErrorThrow(ucp_conn_request_query(conn_request, &attr));
  ucxx::utils::sockaddr_get_ip_port_str(
      &attr.client_address, ip_str, port_str, INET6_ADDRSTRLEN);
  VLOG(3)
      << "Communicator received a connection request from client at address "
      << ip_str << ":" << port_str;

  // incoming endpoints are not shared. Outgoing endpoints to the same node are
  // shared. This guarantees that between any two nodes, there will be at most 2
  // endpoints, one per direction. For compatibility reasons, both incoming and
  // outgoing endpoints are represented using the EndpointRef.
  auto endpoint = listener_->createEndpointFromConnRequest(conn_request, true);
  // Pass the peer's actual address to EndpointRef for diagnostics.
  auto epRef = std::make_shared<EndpointRef>(
      endpoint, std::string(ip_str), std::string(port_str));
  endpoint->setCloseCallback(EndpointRef::onClose, epRef);
  // Add this endpoint reference to the list of endpoints.
  // NOTE: This runs inside a UCX listener callback (during worker progress),
  // so we must not throw — throwing from a UCX callback is undefined behavior.
  unsigned long val = std::strtoul(port_str, nullptr, 10);
  if (val > static_cast<unsigned long>(std::numeric_limits<uint16_t>::max())) {
    LOG(ERROR) << "listenerCallback: port out of range for uint16_t: " << val;
    return;
  }

  uint16_t port = static_cast<uint16_t>(val);
  HostPort hp(ip_str, port);
  {
    std::lock_guard<std::recursive_mutex> lock(endpointsMutex_);
    auto res = endpoints_.insert(std::pair{hp, epRef});
    if (!res.second) {
      LOG(ERROR) << "listenerCallback: endpoint already exists for " << ip_str
                 << ":" << port;
      return;
    }
  }
  acceptor_.registerEndpointRef(epRef);
}

void Communicator::dataListenerCallback(ucp_conn_request_h conn_request) {
  if (shuttingDown_.load(std::memory_order_acquire)) {
    return;
  }
  char ipStr[INET6_ADDRSTRLEN];
  char portStr[INET6_ADDRSTRLEN];
  ucp_conn_request_attr_t attr{};
  attr.field_mask = UCP_CONN_REQUEST_ATTR_FIELD_CLIENT_ADDR;
  ucxx::utils::ucsErrorThrow(ucp_conn_request_query(conn_request, &attr));
  ucxx::utils::sockaddr_get_ip_port_str(
      &attr.client_address, ipStr, portStr, INET6_ADDRSTRLEN);

  auto endpoint =
      dataListener_->createEndpointFromConnRequest(conn_request, false);
  VELOX_CHECK_NOT_NULL(endpoint, "Failed to accept UCX bulk-data endpoint");
  {
    std::lock_guard<std::recursive_mutex> lock(endpointsMutex_);
    incomingDataEndpoints_.push_back(endpoint);
  }
  LOG(INFO) << "Accepted UCX bulk-data endpoint with error handling disabled: "
            << "peer=" << ipStr << ":" << portStr;
}

} // namespace facebook::velox::ucx_exchange
